Add tests inmutable widgets.
yiisoft/widget pull request #22
Opened 2020-11-29 14:37 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii-bulma/pull/20

2020-11-29 14:43 UTC, terabytesoftw commented
We have two types of widgets:

Widget simple:

```php
$widget = MyWidget::Widget();
$widget->render();
```

Widget Begin/End:

```php
$widget = MyWidget::Begin();
$widget->start();
    // content
$widget->end();
```

2020-11-29 14:56 UTC, terabytesoftw commented
Another variant but there will be a great BC:

We have two types of widgets:

Widget simple:

```php
$widget = MyWidget::widget();
$widget->render();
```

Widget begin/end:

```php
$widget = MyWidget::widget();
$widget->begin();
    // content
$widget->end();
```

2020-11-29 15:05 UTC, samdark commented
Do you mean:

```php
$widget = MyWidget::widget()->option1(true)->option2(false);
$widget->begin();
    // content
$widget->end();
```

?

2020-11-29 15:05 UTC, terabytesoftw commented
> Do you mean:
> 
> ```
> $widget = MyWidget::widget()->option1(true)->option2(false);
> $widget->begin();
>     // content
> $widget->end();
> ```
> 
> ?

yes.

2020-11-29 15:12 UTC, samdark commented
In a template that would be:

```php
<?php $widget = MyWidget::widget()->option1(true)->option2(false) ?>
<?= $widget->begin() ?>
    Content
<?= $widget->end() ?>
```

It could also be:

```php
<?= MyWidget::widget()->options(['class' => 'testMe'])->begin() ?>
    // content
<?= MyWidget::end() ?>
```

2020-11-29 15:16 UTC, terabytesoftw commented
> In a template that would be:
> 
> ```
> <?php $widget = MyWidget::widget()->option1(true)->option2(false) ?>
> <?= $widget->begin() ?>
>     Content
> <?= $widget->end() ?>
> ```
> 
> It could also be:
> 
> ```
> <?= MyWidget::widget()->options(['class' => 'testMe'])->begin() ?>
>     // content
> <?= MyWidget::end() ?>
> ```

yes, i have added the test.

2020-11-29 15:23 UTC, samdark requested changes

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $a = TestWidgetA::widget();
```suggestion
        $a = TestWidgetA::widget()->begin();
```

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $b = TestWidgetB::widget();
```suggestion
        $b = TestWidgetB::widget()->begin();
```

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $widget->end();
```suggestion
        TestWidget::end();
```

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $widget->end();
`end()` is a static method.

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $output = $widget->end();
`end()` is a static method.

2020-11-29 15:23 UTC, samdark commented on tests/WidgetTest.php
> +        $widget = TestWidgetA::widget()->id('test')->begin();
```suggestion
        TestWidgetA::widget()->id('test')->begin();
```

2020-11-29 15:39 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $widget = TestWidgetA::widget()->id('test')->begin();
done.

2020-11-29 15:40 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $output = $widget->end();
done.

2020-11-29 15:40 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $widget->end();
done.

2020-11-29 15:40 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $widget->end();
done.

2020-11-29 15:40 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $b = TestWidgetB::widget();
done.

2020-11-29 15:40 UTC, terabytesoftw commented on tests/WidgetTest.php
> +        $a = TestWidgetA::widget();
done.

2020-11-30 14:02 UTC, samdark approved these changes

2020-11-30 15:56 UTC, terabytesoftw commented
Please check I think all the PRs that BC will do in the repositories are ready, are there any missing ?

2020-11-30 21:54 UTC, samdark commented
- auth-client
- dataview
- yii-widgets

I'll fix these.

2020-11-30 22:05 UTC, merged