Add params for configure `WidgetFactory`
yiisoft/widget pull request #45
Opened 2021-11-10 19:34 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2021-11-10 19:54 UTC, devanych approved these changes

2021-11-11 09:53 UTC, samdark requested changes

2021-11-11 09:53 UTC, samdark commented on config/params.php
> +        'widgetsGroup' => 'widgets',
```suggestion
        'configGroup' => 'widgets',
```

2021-11-11 09:53 UTC, samdark commented on config/bootstrap.php
> +            $config->get($params['yiisoft/widget']['widgetsGroup']),
```suggestion
            $config->get($params['yiisoft/widget']['configGroup']),
```

2021-11-11 10:45 UTC, samdark approved these changes

2021-11-11 10:45 UTC, merged

2021-11-11 10:45 UTC, samdark commented
👍